In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a','b','c']
myList = [10,20,30]
print(myList)
pd.Series(myList,index=labels)

[10, 20, 30]

a    10
b    20
c    30
dtype: int64

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
list2 = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns = ['naam','umar','city','salary']
df2= pd.DataFrame(list2,columns=columns)
df2

    naam  umar      city  salary
0   John    28  New York   65000
1   Anna    34     Paris   70000
2  Peter    29    Berlin   62000
3  Linda    42    London   85000

In [ ]:
#section and indexing
df2['naam']

0     John
1     Anna
2    Peter
3    Linda
Name: naam, dtype: object

In [ ]:
df2[['city','umar']]

       city  umar
0  New York    28
1     Paris    34
2    Berlin    29
3    London    42

In [ ]:
df2['gender'] = ['M','F','M','F']

In [ ]:
df2

    naam  umar      city  salary gender
0   John    28  New York   65000      M
1   Anna    34     Paris   70000      F
2  Peter    29    Berlin   62000      M
3  Linda    42    London   85000      F

In [ ]:
df2.drop(['gender'],axis=1,inplace=True)

In [ ]:
df2

    naam  umar      city  salary
0   John    28  New York   65000
1   Anna    34     Paris   70000
2  Peter    29    Berlin   62000
3  Linda    42    London   85000

In [ ]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [ ]:
df2.iloc[3]

naam       Linda
umar          42
city      London
salary     85000
Name: 3, dtype: object

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df.loc[[0,1]][['Age','City']]

   Age      City
0   28  New York
1   34     Paris

In [ ]:
df[df['Age' ]> 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
df[(df['Age' ]> 30) & (df['City'] == 'Paris') ]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

**MISSING DATA**

In [ ]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

**MERGEING AND JOINING**

In [ ]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
pd.merge(employees,salaries , on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries , on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees,salaries , on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees,salaries , on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

**Concatication**

In [ ]:
pd.concat([employees,salaries])

   employee_id   name department   salary    bonus
0            1   John         HR      NaN      NaN
1            2   Anna         IT      NaN      NaN
2            3  Peter    Finance      NaN      NaN
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
0            1    NaN        NaN  60000.0   5000.0
1            2    NaN        NaN  80000.0  10000.0
2            3    NaN        NaN  65000.0   7000.0
3            6    NaN        NaN  70000.0   8000.0
4            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.concat([employees,salaries],axis=1)

   employee_id   name department  employee_id  salary  bonus
0            1   John         HR            1   60000   5000
1            2   Anna         IT            2   80000  10000
2            3  Peter    Finance            3   65000   7000
3            4  Linda         IT            6   70000   8000
4            5    Bob         HR            7   90000  12000

**Grouping**

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
st = df.groupby('Store')
for i,v in st:
  print(i)
  print(v)

S1
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
4        A    S1    120         8 2023-01-05
7        B    S1    300        25 2023-01-08
S2
  Category Store  Sales  Quantity       Date
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07

In [ ]:
st = df.groupby('Store')['Sales'].sum()
st

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
ct = df.groupby(['Store','Category'])['Sales'].sum()
ct

Store  Category
S1     A           220
       B           500
S2     A           350
       B           430
Name: Sales, dtype: int64

In [ ]:
df['Sales'].count()

np.int64(8)

In [ ]:
df['Sales'].agg(['sum', 'mean', 'median'])

sum       1500.0
mean       187.5
median     190.0
Name: Sales, dtype: float64

**Pivot Tables && Cross Tabs**

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    799     67   John  January      Q1
1  2023-01-02       B   West    467     21   Mary  January      Q1
2  2023-01-03       C  North    487     47    Bob  January      Q1
3  2023-01-04       D  South    492     70  Alice  January      Q1
4  2023-01-05       A   East    156     97   John  January      Q1
5  2023-01-06       B   West    460     14   Mary  January      Q1
6  2023-01-07       C  North    563     84    Bob  January      Q1
7  2023-01-08       D  South    938     96  Alice  January      Q1
8  2023-01-09       A   East    315     43   John  January      Q1
9  2023-01-10       B   West    152     47   Mary  January      Q1
10 2023-01-11       C  North    925     52    Bob  January      Q1
11 2023-01-12       D  South    898     91  Alice  January      Q1
12 2023-01-13       A   East    386     71   John  January      Q1
13 2023-01-14       B   West    360     64   Mary  January      Q1
14 2023-01-15       C  North    844     87    Bob  January      Q1
15 2023-01-16       D  South    664     89  Alice  January      Q1
16 2023-01-17       A   East    549     31   John  January      Q1
17 2023-01-18       B   West    733     13   Mary  January      Q1
18 2023-01-19       C  North    399     75    Bob  January      Q1
19 2023-01-20       D  South    770     90  Alice  January      Q1

In [ ]:
rg = df.groupby('Region')
len(rg)

4

In [ ]:
pd.pivot_table(df,index='Region',columns='Product',values='Sales',aggfunc='median') # aggfunc by default mean

Product       A       B       C       D
Region
East     2205.0     NaN     NaN     NaN
North       NaN     NaN  3218.0     NaN
South       NaN     NaN     NaN  3762.0
West        NaN  2172.0     NaN     NaN

In [ ]:
pd.pivot_table(df,index='Region',columns='Product',values=['Sales','Units'],aggfunc='sum')

          Sales                          Units
Product       A       B       C       D      A      B      C      D
Region
East     2205.0     NaN     NaN     NaN  309.0    NaN    NaN    NaN
North       NaN     NaN  3218.0     NaN    NaN    NaN  345.0    NaN
South       NaN     NaN     NaN  3762.0    NaN    NaN    NaN  436.0
West        NaN  2172.0     NaN     NaN    NaN  159.0    NaN    NaN

**Operations**

In [ ]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df1.shape

(5, 3)

In [ ]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [ ]:
def square(x):
  return x*x

In [ ]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df1['D'] = df1['B'].apply(square)

In [ ]:
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000